### ISSUE TITLE
openmm_dev channel is missing Python 3.11

### ISSUE THREAD

**Issue by bdenhollander** [conda-forge/openmm-feedstock#104]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The [main channel](https://anaconda.org/conda-forge/openmm/files?channel=main) has py311 builds but [openmm_dev](https://anaconda.org/conda-forge/openmm/files?channel=openmm_dev) has py310 as the newest Python version.

I was able to install the dev version by specifying python=3.10, which forced mamba to downgrade the environment from Python 3.11.

Please add py311 builds for openmm_dev.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by mikemhenry** [comment]
@bdenhollander Thanks for opening this issue! I will do a new dev build now and add python 3.11

**Comment by mikemhenry** [comment]
Just merged in #106 Fresh python 3.11 builds will be available soon. Once CI gets them uploaded, I will close this issue (and the one in the openmm repo)
