### ISSUE TITLE
osx-arm64

### ISSUE THREAD

**Issue by jchodera** [conda-forge/openmm-feedstock#43]
@jaimergp : Do we have a plan to add [osx-arm64](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/) builds for OpenMM yet?

**Comment by isuruf** [comment]
@jchodera, send a PR to add `openmm` to the list at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt

**Comment by jaimergp** [comment]
Done, @jchodera! Thanks @isuruf

**Comment by jchodera** [comment]
Thanks, @isuruf and @jaimergp!

**Comment by jaimergp** [comment]
For our readers, work is being done on #44
