### ISSUE TITLE
Add a build variant without ocl-icd / ocl-icd-system for required compatibility with some use cases

### ISSUE THREAD

**Issue by jchodera** [conda-forge/openmm-feedstock#57]
We've run into an issue rebuilding OpenMM-based compute cores for Folding@home from the conda-forge package where the `ocl-icd` interferes with the ability to use the system OpenCL libraries on `linux`.

We'd like to add a build variant that lacks the `ocl-icd` related packages so the build links directly to the system OpenCL.

This would not be the default variant, so compatibility with other conda-forge packages should be maintained except under special circumstances that the build variant is specifically selected.

@jaimergp: Any chance we could contract you to help with these changes?

**Comment by isuruf** [comment]
@jchodera, please avoid spreading FUD and report on the exact issue that you are having. There's an issue template here where you can provide more information on.

**Comment by peastman** [comment]
@jchodera or @dotsdl can you provide more information about this?  If we're going to make changes to the variants, we need to decide in the next few weeks.  Can you describe what the issues are?

**Comment by jchodera** [comment]
@peastman: The issues are meticulously documented in the internal openmm FAH core issue tracker [here](https://github.com/FoldingAtHome/openmm-core/pull/371), which you have access to, but I've asked @dotsdl to summarize the issues here since that isn't public.

**Comment by peastman** [comment]
Since no one else has replied, I'll do my best to summarize the issue here.  Hopefully someone else can fill in more details.

The problem is that the version built against ocl-icd is nonfunctional outside of a conda environment.

The core of OpenMM is a set of C++ libraries.  They also have APIs for C and Fortran.  Users can write applications in any of those languages that link to OpenMM.  When used in this way, there is no conda environment, and in fact no Python at all.  It's just a native application linking to native libraries.  The developers of those applications typically bundle the OpenMM libraries with them.  But if the libraries were linked to ocl-icd, they don't function properly outside of a conda environment and therefore aren't suitable for many of our users.

**Comment by jchodera** [comment]
To be specific about our use case for Folding@home (and one that others likely need to follow): Using the conda-installed build environment via conda-forge _enormously_ simplifies our build process, since we can easily install a fully ABI-compatible set of libraries and dependencies. The only hitch is that redistributing the `ocl-icd`'s `libOpenCL.so` on linux results in a failure to find the vendor OpenCL implementations. 

In previous builds of the Folding@home OpenMM core (pre-conda-forge), when we link to a vendor OpenCL implementation (such as the one already in the CUDA toolkit) directly, but don't ship `libOpenCL.so`, it works fine. We tested this at scale on hundreds of thousands of installs.

We'd like to add an experimental build variant that would link directly to the CUDA `libOpenCL.so` if the variant is requested and test this out. If it addresses this issue, then it would be tremendously useful and should not cause any compatibility problems with default installations. We could call the variant something obvious, like `cuda-opencl`, to make it clear that we were specifically and only linking to the corresponding CUDA version.

**Comment by isuruf** [comment]
> The only hitch is that redistributing the ocl-icd's libOpenCL.so on linux results in a failure to find the vendor OpenCL implementations.

Please describe this issue in detail. How does this happen?

**Comment by peastman** [comment]
Note that the libOpenCL.so installed with the GPU driver actually comes from Khronos.  That's true whether the GPU is from NVIDIA, AMD, or Intel.  They all install the same library.  There's nothing CUDA-specific about it, so I would call the variant `khronos-opencl`.

**Comment by dotsdl** [comment]
> > The only hitch is that redistributing the ocl-icd's libOpenCL.so on linux results in a failure to find the vendor OpenCL implementations.
> 
> Please describe this issue in detail. How does this happen?

Because OpenMM is compiled with `ocl-icd` present, when the Folding@home core (which includes the OpenMM compiled artifacts) lands on a volunteer host, OpenMM is dependent on an `ocl-icd` implementation on that host for proper functioning. This is not guaranteed to be present, and in enough cases is not. It is also not something we can ship with the core itself and expect it to work as we do for other required shared libraries.

This issue has been previously avoided by linking directly to the NVIDIA-vendored `OpenCL` library. This solution appears remarkably robust, even when the volunteer host has e.g. an AMD GPU. As @peastman pointed out, this is because other vendors distribute the Khronos OpenCL implementation.

@isuruf I notice that there is no Linux variant for the [`khronos-opencl-icd-loader` package](https://anaconda.org/conda-forge/khronos-opencl-icd-loader/files). We use this package for our Windows builds of the OpenMM core, and haven't seen this issue with OpenCL on Windows. It's unclear to me that having a Linux variant of this package would solve this issue in a different way, but wanted to note it as a possible alternate path.

**Comment by isuruf** [comment]
> Because OpenMM is compiled with ocl-icd present, when the Folding@home core (which includes the OpenMM compiled artifacts) lands on a volunteer host, OpenMM is dependent on an ocl-icd implementation on that host for proper functioning. This is not guaranteed to be present, and in enough cases is not. 

I still don't understand what the error is. 

> It is also not something we can ship with the core itself and expect it to work as we do for other required shared libraries.

What does this mean? Please describe in more detail

**Comment by dotsdl** [comment]
@isuruf I'll try to produce and provide a minimal working example. I recognize that this issue is buried in some complexity.

In the meantime, could it be worthwhile pursuing a Linux build of the `khronos-opencl-icd-loader` package? It's not clear yet if that would solve our problem, but if it does, it may actually be the most elegant solution available to us. Is there a reason there isn't already a Linux build of this package?

**Comment by isuruf** [comment]
> In the meantime, could it be worthwhile pursuing a Linux build of the khronos-opencl-icd-loader package? It's not clear yet if that would solve our problem, but if it does, it may actually be the most elegant solution available to us.

Probably not. This is a classic XY problem, where all I know so far is Y problem and it's not clear to me what X is.

> Is there a reason there isn't already a Linux build of this package?

`ocl-icd` and `khronos-opencl-icd-loader` has the same functionality, but `ocl-icd` provides better diagnostics via env variables and had a OSF approved license at the time we considered both. (`khronos-opencl-icd-loader` had a weird license and now it's Apache-2)

**Comment by dotsdl** [comment]
Reproducible example below; see bottom for follow-up questions. 

---------

With the following conda env 

```
# env.yml
name: openmm-ocl-test
channels:
- conda-forge
dependencies:
# build
- cmake
- make
- ccache
# host
- python 3.6.*
- cython
- swig
- numpy
- doxygen 1.8.14
- git
- scons
- zip
# direct dependencies
- fftw
- libopenssl-static 1.1.1k
- openssl 1.1.1k
- compilers
- cudatoolkit 10.2.*

# adjust below as desired
# do not use > or <
- openmm 7.5.1
```

OpenMM runs as expected with a:

```
conda env create -f env.yml
conda activate openmm-ocl-test
cd $CONDA_PREFIX/share/openmm/examples
```

Creating the file `simulatePdb-opencl.py`:
```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

pdb = PDBFile('input.pdb')

platform = Platform.getPlatformByName('OpenCL')

forcefield = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)

simulation = Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
simulation.step(10000)
```

And running with:
```
python simulatePdb-opencl.py
```
works just fine.

Removing `ocl-icd-system` with:
```
conda remove --force ocl-icd-system
```

Gives an error when running `python simulatePdb-opencl.py`:
```
simtk.openmm.OpenMMException: There is no registered Platform called "OpenCL"
```

Removing `ocl-icd` with `conda remove --force ocl-icd` and running `python simulatePdb-opencl.py`, however, works fine again.

------
This was performed on an Arch Linux host with the following nvidia and opencl packages:
```
local/cuda 11.3.1-1
    NVIDIA's GPU programming toolkit
local/egl-wayland 1.1.7-1
    EGLStream-based Wayland external platform
local/lib32-nvidia-utils 465.31-1
    NVIDIA drivers utilities (32-bit)
local/libnvidia-container-bin 1.4.0-1
    NVIDIA container runtime library
local/libnvidia-container-tools-bin 1.4.0-1
    NVIDIA container runtime library (command-line tools)
local/libvdpau 1.4-1
    Nvidia VDPAU library
local/libxnvctrl 465.31-1
    NVIDIA NV-CONTROL X extension
local/nvidia 465.31-14
    NVIDIA drivers for linux
local/nvidia-container-toolkit 1.5.0-2
    NVIDIA container runtime toolkit
local/nvidia-settings 465.31-1
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 465.31-1
    NVIDIA drivers utilities
local/opencl-nvidia 465.31-1
    OpenCL implemention for NVIDIA
local/clinfo 3.0.21.02.21-1
    Simple OpenCL application that enumerates all available platform and device properties
local/ocl-icd 2.3.0-1
    OpenCL ICD Bindings
```

When we remove `ocl-icd-system`, I *think* it's the case that then the only OpenCL implementation visible to OpenMM is the OpenCL provided by `ocl-icd`. This doesn't appear to be functional for OpenMM in a meaningful way, unless I'm misunderstanding its purpose?

I should also note: removing just `ocl-icd` and *not* `ocl-icd-system` retains OpenCL functionality with OpenMM. `ocl-icd` appears in this case to be unnecessary to use of OpenMM.

----

If NVIDIA, Intel, and AMD all ship Khronos OpenCL, would it be better to link against this on Linux? Is there any point in having `ocl-icd` as a dependency if we can't run OpenMM with it?

Would linking against Khronos OpenCL also alleviate the need for `ocl-icd` to be present on the host at all for OpenCL to work for the `openmm-core` we ship for Folding@Home? This is less clear to me at this time, but given past experience from @jchodera volunteers for F@H haven't needed to have an `ocl-icd` package installed for OpenCL to work out of the box for that core.

**Comment by isuruf** [comment]
So, let me get this clear. You are saying you removed a dependency of `openmm` (`ocl-icd`) forcefully using `--force` and now `openmm` doesn't work? Please stop wasting my time.

**Comment by jchodera** [comment]
@isuruf : Let me back up a bit here to give some more context, since we seem to have ended up in a place where the problem seems to be mischaracterized by your comment.

The conda-forge builds of OpenMM have solved an enormous variety of issues for deploying OpenMM on various system when conda Python installations are possible. We also operate the [Folding@home](http://foldingathome.org) network, which consists of hundreds of thousands of folks around the world that run the Folding@home client to donate their computing time to causes like the [COVID Moonshot](http://postera.ai/covid), where we are in the final stages of lead optimization for a low-cost, patent-free oral antiviral (a pill) for COVID-19 that we're trying to rush into the clinic as fast as humanly possible.

We have converted the build system for Folding@home OpenMM cores to use the new conda-forge build environment to install compatible prebuilt dependencies for OpenMM and the OpenMM core wrapper. This works magnificently on `win`, almost works perfectly on `linux` (except for the issue we are discussing here), and will also let us build for `osx` very easily. The build process ends up distributing just a binary and libraries, rather than a whole conda installation (which we can't distribute due to technical limitations), but this works great---again, except for this issue.

This issue is just about requesting that we provide a single build variant for a single version of CUDA that would optionally allow linking directly to the standardized Khronos OpenCL library distributed within the CUDA toolkit. If we can do this, we're good to go and can fully deploy on all hundreds of thousands of systems with minimal additional effort. This would only add a single build variant to the matrix, and feeds a use case that---last year---ran up to [a million systems](https://www.choderalab.org/publications/2020/7/5/citizen-scientists-create-an-exascale-computer-to-combat-covid-19).

We really appreciate your engagement and help in this issue. I know you're looking out for maintaining maximum compatibility within the conda-forge universe, which is awesome. This additional optional variant should not disrupt that, and would serve critical use cases like ours (and others that develop with OpenMM software). GPU-enabled builds are still relatively new to conda-forge, so I hope that this kind of optional flexibility---when required to serve significant use cases---is something that would not be problematic.

We're happy to arrange a time for a call if other details are lacking, since it's been difficult to communicate the technical issues and context in this thread.

**Comment by isuruf** [comment]
You say that I mischaracterized the problem. If so, please correct me. @dotsdl's last comment was the most useful and most understandable comment in this thread. If @dotsdl is not correct, please correct it and then we can discuss more.

To summarize @dotsdl's comment.
1. Removing `ocl-icd-system` and keeping `ocl-icd` doesn't work
2. Removing `ocl-icd` and `ocl-icd-system` works.
3. Keeping both works.

Please explain if I misunderstood this.

**Comment by peastman** [comment]
> Please explain if I misunderstood this.

I described the issues in https://github.com/conda-forge/openmm-feedstock/issues/57#issuecomment-893786249, and @jchodera described them further in https://github.com/conda-forge/openmm-feedstock/issues/57#issuecomment-894680891.  Let me emphasize this once again: *OpenMM is frequently used as a C++ library in standalone, native applications that do not involve either a conda environment or python*.  We need a build variant that functions correctly for that purpose.  All that is required is that it link to the standard Khronos ICD loader in place of the non-standard ocl-icd package.

**Comment by isuruf** [comment]
Please see my comment above. You are trying to use 1 which doesn't work. Why not use 2 or 3?

**Comment by peastman** [comment]
@dotsdl I think this is a question for you.  I plan to build the release candidate next week, so if you need this in the next release, we need to resolve this in the next few days.

**Comment by dotsdl** [comment]
> So, let me get this clear. You are saying you removed a dependency of `openmm` (`ocl-icd-system`) forcefully using `--force` and now `openmm` doesn't work? Please stop wasting my time.

This is not a typical end-user issue, but it is an entirely valid use of OpenMM, as [@peastman points out](https://github.com/conda-forge/openmm-feedstock/issues/57#issuecomment-894690002). Here is a detailed explanation of how we are using the `conda-forge` OpenMM Linux builds to support the work of Folding@Home.

All steps below are performed in a Docker instance of the `conda-forge` build anvil `quay.io/condaforge/linux-anvil-comp7`.
1. We create and activate the following `conda` env as the basis for our build:

```yaml
name: build
channels:
- conda-forge
dependencies:
# build
- cmake
- make
- ccache
# host
- python 3.6.*
- cython
- swig
- numpy
- doxygen 1.8.14
- git
- scons
- zip
# direct dependencies
- fftw
- libopenssl-static 1.1.1k
- openssl 1.1.1k
- compilers
- cudatoolkit 10.2.*

# adjust below as desired
# do not use > or <
- openmm 7.5.1

```

2. We build immediate `openmm-core` dependencies, such as [cbang](https://github.com/CauldronDevelopmentLLC/cbang), in this environment.
3. We build `openmm-core` itself.
4. We gather into a tarchive the built core (`FahCore`) and all shared object libraries from the conda build environment it requires to run on volunteer systems:

```
FahCore
libcufft.so.10
libfftw3f.so.3
libfftw3f_threads.so.3
libnvrtc-builtins.so
libnvrtc.so.10.2
libOpenMM.so.7.5
libOpenMMAmoeba.so
libOpenMMAmoebaCUDA.so
libOpenMMAmoebaReference.so
libOpenMMCPU.so
libOpenMMCUDA.so
libOpenMMCudaCompiler.so
libOpenMMDrude.so
libOpenMMDrudeCUDA.so
libOpenMMDrudeOpenCL.so
libOpenMMDrudeReference.so
libOpenMMOpenCL.so
libOpenMMPME.so
libOpenMMRPMD.so
libOpenMMRPMDCUDA.so
libOpenMMRPMDOpenCL.so
libOpenMMRPMDReference.so
```

In production on Folding@Home, volunteers run the Folding@Home client on their home machines. For volunteers with a Linux host, the client will pull this tarchive, unpack it, and run the built core (`FahCore`) on a job pulled from any of a number of work servers managed at consortium member sites. The core will use the shared libraries present alongside it in addition to those on the host system to then execute the job.

For users that do not have an `ocl-icd` loader implementation installed on their host (e.g. on Ubuntu the package `ocl-icd-libopencl1`), running the core will fail to create an OpenCL context on the target GPU. We are looking for a solution to this problem that does not require users to configure their systems any further than having the appropriate driver installed for their GPU and the Folding@Home client itself.

Some proposed solutions from discussions so far:
1. Distribute the `ocl-icd` loader alongside the core, as we do for shared object libs. I'm not sure exactly if this is simple, or if there is more to it than just dropping some additional components from the conda build env into the tarchive.
2. Use a build of OpenMM that isn't built against `ocl-icd`, but instead is built against the Khronos implementation of OpenCL, [which the major GPU vendors all ship](https://github.com/conda-forge/openmm-feedstock/issues/57#issuecomment-894347713) themselves. This may avoid needing to rely on an ICD loader present on the volunteer system at all. Notably, this is what we already do for [OpenMM `conda-forge` builds on Windows and OSX](https://github.com/conda-forge/openmm-feedstock/blob/502474e83a67349431b635337532d737891724b5/recipe/meta.yaml#L64).

**Comment by isuruf** [comment]
If you are not distributing `ocl-icd` loader alongside the core, can you please explain to me how you are running into an issue with OpenCL?

**Comment by isuruf** [comment]
Your own statement seems to contradicate your last comment.

> Removing ocl-icd with conda remove --force ocl-icd and running python simulatePdb-opencl.py, however, works fine again.

**Comment by dotsdl** [comment]
Previously, we tried shipping the `libOpenCL.so.1.0.0` from the `ocl-icd` `conda-forge` package as `libOpenCL.so.1` alongside the core. The core could not create an OpenCL context for any volunteer GPUs with this present.

**Comment by isuruf** [comment]
That's clearly option 1 which doesn't work. Option 3 requires you to ship `ocl-icd-system` which is the symlink in `$CONDA_PREFIX/etc/OpenCL/vendors/ocl-icd-system`

**Comment by isuruf** [comment]
Option 3 wouldn't work if you are not using conda's relocation code. So, you'd have to set env variable `OCL_ICD_VENDORS=/etc/OpenCL/vendors` or go with Option 2 which is not shipping libOpenCL.so.1

**Comment by peastman** [comment]
To be clear, are you saying that the libOpenCL.so from ocl-icd is not binary compatible with the standard libOpenCL.so?  Such that a library compiled against the former cannot link to and use the latter?

**Comment by dotsdl** [comment]
Currently we are not shipping `libOpenCL.so.1` with the core, but this requires an ICD loader present on the host system (e.g. on Ubuntu the package `ocl-icd-libopencl1`) to work. We are trying to find a solution or workaround to that.

Is setting `OCL_ICD_VENDORS=/etc/OpenCL/vendors` known to work without an ICD loader present on the system? If so, this could be an alternative to building OpenMM with Khronos and shipping its `libOpenCL` with the core.

**Comment by isuruf** [comment]
> To be clear, are you saying that the libOpenCL.so from ocl-icd is not binary compatible with the standard libOpenCL.so? Such that a library compiled against the former cannot link to and use the latter?

No, they are binary compatible except for the default location that it looks for ICDs.

> Currently we are not shipping libOpenCL.so.1 with the core, but this requires an ICD loader present on the host system (e.g. on Ubuntu the package ocl-icd-libopencl1) to work. We are trying to find a solution or workaround to that.

I don't know what you are hoping to accomplish with a loader if you don't have OpenCL installed on the host.

> Is setting OCL_ICD_VENDORS=/etc/OpenCL/vendors known to work without an ICD loader present on the system? I

Yes. You have to set that AND ship `libOpenCL.so.1`

**Comment by isuruf** [comment]
> Currently we are not shipping libOpenCL.so.1 with the core, but this requires an ICD loader present on the host system (e.g. on Ubuntu the package ocl-icd-libopencl1) to work. We are trying to find a solution or workaround to that.

I'm still confused. How would your original objective of building openmm without ocl-icd help in this case?

**Comment by dotsdl** [comment]
> > Is setting OCL_ICD_VENDORS=/etc/OpenCL/vendors known to work without an ICD loader present on the system? I
> 
> Yes. You have to set that AND ship `libOpenCL.so.1`

Thanks @isuruf, this detail inspired me to try the following, based on [item 1](https://github.com/conda-forge/openmm-feedstock/issues/57#issuecomment-894682327):

Removing `ocl-icd-system` and keeping `ocl-icd` doesn't work. However, as you might expect, setting `OCL_ICD_VENDORS="/etc/OpenCL/vendors"` restores functionality provided by the `ocl-icd-system` package.

I believe we can take the following approach for the `openmm-core`, which I am pursuing now to see if there are further showstoppers:

1. Ship `libOpenCL.so.1` from `ocl-icd` with the core.
2. Set `OCL_ICD_VENDORS="/etc/OpenCL/vendors"`, within the core itself or in the calling client.

This should be sufficient for getting OpenCL to work as desired on volunteer hosts for a variety of GPU vendors.

The manpage for `LIBOPENCL(7)` clarified this for me, along with your comment:

```
$ man 7 libOpenCL
LIBOPENCL(7)                                                                                                                                                             LIBOPENCL(7)

NAME
       libOpenCL, libOpenCL.so - OCL-ICD implementation of OpenCL ICD loader

DESCRIPTION
       libOpenCL.so is the library linked by OpenCL programs. It does not contains any OpenCL implementation itself, but merely act as a dispatcher to real OpenCL implementations
       provided as OpenCL Installable Client Driver (ICD). An ICD loader should be able to load ICDs provided by any vendors.

       According to OpenCL specifications from Khronos (see [Khronos]), the ICD Loader looks for files into /etc/OpenCL/vendors directory and, for each file whose name ends with
       .icd, the ICD Loader loads with dlopen(3) the shared library whose name is on the first line of the .icd file.

       Each shared library name in ".icd" files can have its path, or it can be a plain filename. In the latter case, the ICD shared library will be looked for into the standard
       dynamic library loader paths.

ENVIRONMENT
       Some environment variables can be used modify the default behavior of libOpenCL.

       OPENCL_VENDOR_PATH
           This variable allows one to modify the default /etc/OpenCL/vendors path. It is compatible with some other ICD loaders (but not all of them, as the variable is not part of
           the standard). Note that $OCL_ICD_VENDORS (see below) is used in priority if defined and not empty.

       OCL_ICD_VENDORS
           This variable allows one to change the way ICD are searched on the system. Several cases are considered:

            1. if $OCL_ICD_VENDORS is a directory path, then this path replaces the "/etc/OpenCL/vendors" path in the standard behavior: the loader will use the .icd files in this
               directory;

            2. else, if $OCL_ICD_VENDORS ends with .icd, libOpenCL.so will only load the ICD whose shared library name is wrote into the specified ".icd" file;

               If there is no slashes into $OCL_ICD_VENDORS, libOpenCL.so will first try to use /etc/OpenCL/vendors/$OCL_ICD_VENDORS (or $OPENCL_VENDOR_PATH/$OCL_ICD_VENDORS if
               OPENCL_VENDOR_PATH is defined). If this fail or if there are shashes, it uses $OCL_ICD_VENDORS (as a relative or absolute file name path).

            3. else libOpenCL.so will try to load $OCL_ICD_VENDORS as the ICD shared library itself (i.e. to load it directly with dlopen(3)).
```

**Comment by dotsdl** [comment]
We have addressed this issue in the `openmm-core` build by inclusion of non-conda-forge `ocl-icd` `libOpenCL` with the built core. This issue can be closed.

Thank you everyone for your help in understanding this issue; these discussions helped us to arrive at a workable solution.

**Comment by peastman** [comment]
Thanks!
