### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by isuruf** [conda-forge/openmm-feedstock#9]
It looks like this package violates the license of `lepton` and `lbfgs`. Please include their license files in `about/license_file` which can be a yaml list.

**Comment by jchodera** [comment]
Thanks for catching this, and thanks so much for the pointers!

**Comment by jakirkham** [comment]
Would it be possible to break those out as separate packages that `openmm` depends on?

**Comment by jchodera** [comment]
> Would it be possible to break those out as separate packages that openmm depends on?

We've discussed this previously with @peastman and it didn't make sense to split them into separate source trees, but that doesn't preclude us from splitting them into separate conda packages.

**Comment by peastman** [comment]
Lepton is part of OpenMM, so there isn't a separate license for it.

**Comment by jchodera** [comment]
cc: https://github.com/conda-forge/openmm-feedstock/pull/11

**Comment by jchodera** [comment]
Fixed by https://github.com/conda-forge/openmm-feedstock/pull/11
